### ISSUE TITLE
Page Picker: Pages with a redirect not visible

### ISSUE THREAD

**Issue by pascalmoser** [2sic/2SexyContent#181] opened 2015-03-20 13:57 UTC
The page picker does not show pages which have a redirect configured.

**Comment by iJungleboy** [comment] 2015-04-26 21:21
Why would you want to point to a page which redirects? I mean, it redirects to somewhere else anyhow...

**Comment by raphael-m** [comment] 2015-04-27 06:32
The problem is that the subpages of those pages are not visible.

**Comment by iJungleboy** [comment] 2015-04-27 06:44
Ok. But I assume this is a "standard" dnn feature, right?
In that case, we won't try to fix it ourselves - simply out of scope. Though it's not nice, it's easy to work around. 
Because of this I'll close this for now. If you see any need, please post to DNN.

**Closed by iJungleboy** 2015-04-27 06:44 UTC

**Comment by raphael-m** [comment] 2015-04-27 07:23
@iJungleboy, I'm not sure if it's a DNN standard "feature"... maybe we could add a property to the page picker control to make redirecting pages visible.

**Comment by raphael-m** [comment] 2015-04-27 07:24
Looks like the property is called **IncludeAllTabTypes**: [DNN-3878](https://dnntracker.atlassian.net/browse/DNN-3878)
