### ISSUE TITLE
After changing the DNN Site Alias configuration all 2sic apps stopped working

### ISSUE THREAD

**Issue by mconta** [2sic/2SexyContent#124] opened 2014-12-23 14:17 UTC
After changing the site alias configuration all 2sic apps stopped working

Errors returned to client:
An error has occurred. Error: <app name> is currently unavailable.

Error returned in editing mode:
Error: Customer - <appname> is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: App with id 4 doesn't exist. Parameter name: appId ---> System.ArgumentException: App with id 4 doesn't exist. Parameter name: appId at ToSic.Eav.EavContext.InitZoneApp(Nullable`1 zoneId, Nullable`1 appId) at ToSic.SexyContent.SexyContent..ctor(Int32 zoneId, Int32 appId, Boolean enableCaching, Nullable`1 ownerPortalId) at ToSic.SexyContent.SexyControlEditBase.get_Sexy() at ToSic.SexyContent.ViewApp.Page_PreRender(Object sender, EventArgs e) --- End of inner exception stack trace ---

This problem is really blocking.

UPDATE : 
it seems that the cause isn't the update to the new DNN version. See comments in the bottom

**Comment by raphael-m** [comment] 2015-02-13 16:56
Were you able to solve the issue, even with the "not working" PortalAlias configuration?
2sxc saves the "ZoneId" as a PortalSetting, I assume that the issue is that 2sxc somehow can't find the setting.

**Comment by iJungleboy** [comment] 2015-02-17 10:50
Hi Mateo
We believe it's not a 2sxc issue, but that your problem was that you didn't set a primary ID for the language it-IT. 
We'll close the issue now.

**Closed by iJungleboy** 2015-02-17 10:50 UTC

**Comment by mconta** [comment] 2015-02-18 13:48
Hi iJungleBoy, I think you are correct, if I find a way to reproduce and document the problem I will inform you using this thread. Thanks
